name: CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    name: Check types, lint, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel Environment Information
        run: npm_config_yes=true npx vercel env pull .env --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Run format
        run: npm run format

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test

  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Pull Vercel Environment Information
        run: npm_config_yes=true npx vercel env pull .env --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build
        run: dotenv -- npm run build
